<a href="https://colab.research.google.com/github/logiha/northstar-database-analytics/blob/main/NorthStar_MongoDBipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

base_url = "https://raw.githubusercontent.com/logiha/northstar-database-analytics/main/"

customers = pd.read_csv(base_url + "customers.csv")
orders = pd.read_csv(base_url + "orders.csv")
deliveries = pd.read_csv(base_url + "deliveries.csv")
complaints = pd.read_csv(base_url + "complaints.csv")
vehicles = pd.read_csv(base_url + "vehicles.csv")
incidents = pd.read_csv(base_url + "incidents.csv")
drivers = pd.read_csv(base_url + "drivers.csv")
hubs = pd.read_csv(base_url + "hubs.csv")
app_events = pd.read_csv(base_url + "app_events.csv")

print(deliveries.shape)
print(orders.shape)
print(customers.shape)

(950, 13)
(1250, 11)
(650, 9)

In [ ]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 29.2 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 19.1 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0

In [ ]:
from pymongo import MongoClient
import pandas as pd

In [ ]:
import pandas as pd

deliveries = pd.read_csv('/content/deliveries.csv')

deliveries.head()

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

In [ ]:
delivery_docs = deliveries.to_dict("records")

delivery_docs[0]

{'delivery_id': 'DL00001',
 'order_id': 'O00938',
 'driver_id': 'D004',
 'vehicle_id': 'V056',
 'hub_id': 'H05',
 'dispatch_time': '2024-06-18 10:57:00',
 'delivery_completed_at': '2024-06-19 09:05:59.904311',
 'delivery_status': 'Failed',
 'route_distance_km': 17.26,
 'manual_route_override_count': 1,
 'proof_of_completion_missing': 0,
 'customer_rating_post_delivery': 3.07,
 'fuel_or_charge_cost': 12.05}

In [ ]:
len(delivery_docs)

950

In [ ]:
!pip install mongomock

Collecting mongomock
  Downloading mongomock-4.3.0-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from mongomock) (26.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from mongomock) (2025.2)
Collecting sentinels (from mongomock)
  Downloading sentinels-1.1.1-py3-none-any.whl.metadata (3.0 kB)
Downloading mongomock-4.3.0-py2.py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 3.0 MB/s eta 0:00:00
Downloading sentinels-1.1.1-py3-none-any.whl (3.7 kB)
Installing collected packages: sentinels, mongomock
Successfully installed mongomock-4.3.0 sentinels-1.1.1

In [ ]:
import mongomock

client = mongomock.MongoClient()
db = client["northstar_db"]

delivery_collection = db["deliveries"]

delivery_collection.insert_many(delivery_docs)

delivery_collection.count_documents({})

950

In [ ]:
# Find delayed deliveries

list(
    delivery_collection.find(
        {"delivery_status": "Delayed"}
    ).limit(5)
)

[{'delivery_id': 'DL00004',
  'order_id': 'O00313',
  'driver_id': 'D116',
  'vehicle_id': 'V055',
  'hub_id': 'H02',
  'dispatch_time': '2024-03-08 23:31:00',
  'delivery_completed_at': '2024-03-09 23:30:08.103702',
  'delivery_status': 'Delayed',
  'route_distance_km': 16.42,
  'manual_route_override_count': 0,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 4.18,
  'fuel_or_charge_cost': 13.62,
  '_id': ObjectId('6a12a72872d2ac021c56bdb4')},
 {'delivery_id': 'DL00006',
  'order_id': 'O00029',
  'driver_id': 'D037',
  'vehicle_id': 'V098',
  'hub_id': 'H03',
  'dispatch_time': '2024-09-11 12:40:00',
  'delivery_completed_at': '2024-09-12 17:11:52.384869',
  'delivery_status': 'Delayed',
  'route_distance_km': 13.84,
  'manual_route_override_count': 0,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 1.57,
  'fuel_or_charge_cost': 9.58,
  '_id': ObjectId('6a12a72872d2ac021c56bdb6')},
 {'delivery_id': 'DL00007',
  'order_id': 'O00097',
  'driver_id': 'D151',
  'vehicle_id': 'V037',
  'hub_id': 'H07',
  'dispatch_time': '2024-01-09 13:41:00',
  'delivery_completed_at': '2024-01-10 23:39:11.072850',
  'delivery_status': 'Delayed',
  'route_distance_km': 32.72,
  'manual_route_override_count': 0,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 4.64,
  'fuel_or_charge_cost': 17.7,
  '_id': ObjectId('6a12a72872d2ac021c56bdb7')},
 {'delivery_id': 'DL00017',
  'order_id': 'O01249',
  'driver_id': 'D002',
  'vehicle_id': 'V008',
  'hub_id': 'H05',
  'dispatch_time': '2024-08-25 18:26:00',
  'delivery_completed_at': '2024-08-26 03:05:42.086626',
  'delivery_status': 'Delayed',
  'route_distance_km': 20.79,
  'manual_route_override_count': 0,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 1.0,
  'fuel_or_charge_cost': 15.62,
  '_id': ObjectId('6a12a72872d2ac021c56bdc1')},
 {'delivery_id': 'DL00028',
  'order_id': 'O00087',
  'driver_id': 'D165',
  'vehicle_id': 'V022',
  'hub_id': 'H08',
  'dispatch_time': '2024-11-12 15:52:00',
  'delivery_completed_at': '2024-11-13 04:15:00.393100',
  'delivery_status': 'Delayed',
  'route_distance_km': 15.53,
  'manual_route_override_count': 2,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 2.7,
  'fuel_or_charge_cost': 13.05,
  '_id': ObjectId('6a12a72872d2ac021c56bdcc')}]

In [ ]:
# Count failed deliveries

delivery_collection.count_documents(
    {"delivery_status": "Failed"}
)

132

In [ ]:
# Aggregation pipeline

pipeline = [
    {
        "$group": {
            "_id": "$delivery_status",
            "average_rating": {
                "$avg": "$customer_rating_post_delivery"
            }
        }
    }
]

list(delivery_collection.aggregate(pipeline))

[{'average_rating': nan, '_id': 'Delayed'},
 {'average_rating': nan, '_id': 'Failed'},
 {'average_rating': nan, '_id': 'OnTime'}]

In [ ]:
deliveries['customer_rating_post_delivery'] = pd.to_numeric(
    deliveries['customer_rating_post_delivery'],
    errors='coerce'
)

deliveries_clean = deliveries.dropna(
    subset=['customer_rating_post_delivery']
)

delivery_docs = deliveries_clean.to_dict("records")

delivery_collection.delete_many({})

delivery_collection.insert_many(delivery_docs)

delivery_collection.count_documents({})

936

In [ ]:
pipeline = [
    {
        "$group": {
            "_id": "$delivery_status",
            "average_rating": {
                "$avg": "$customer_rating_post_delivery"
            }
        }
    }
]

list(delivery_collection.aggregate(pipeline))

[{'average_rating': 3.11497461928934, '_id': 'Delayed'},
 {'average_rating': 3.0493129770992367, '_id': 'Failed'},
 {'average_rating': 4.28327302631579, '_id': 'OnTime'}]

In [ ]:
pipeline = [
    {
        "$group": {
            "_id": "$delivery_status",
            "average_override": {
                "$avg": "$manual_route_override_count"
            }
        }
    }
]

list(delivery_collection.aggregate(pipeline))

[{'average_override': 1.0710659898477157, '_id': 'Delayed'},
 {'average_override': 1.0229007633587786, '_id': 'Failed'},
 {'average_override': 0.9276315789473685, '_id': 'OnTime'}]

In [ ]:
delivery_collection.create_index("delivery_status")

'delivery_status_1'

In [ ]:
delivery_collection.create_index([
    ("hub_id", 1),
    ("delivery_status", 1)
])

'hub_id_1_delivery_status_1'

In [ ]:
delivery_collection.index_information()

{'_id_': {'key': [('_id', 1)], 'v': 2},
 'delivery_status_1': {'key': [('delivery_status', 1)], 'v': 2}}

In [4]:
!pip install pymongo mongomock

Collecting pymongo
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting mongomock
  Downloading mongomock-4.3.0-py2.py3-none-any.whl.metadata (12 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from mongomock) (26.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from mongomock) (2025.2)
Collecting sentinels (from mongomock)
  Downloading sentinels-1.1.1-py3-none-any.whl.metadata (3.0 kB)
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 5.7 MB/s eta 0:00:00
Downloading mongomock-4.3.0-py2.py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 3.9 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 19.7 MB/s eta 0:00:00
Downloading sentinels-1.1.1-py3-none-any.whl (3.7 kB)
Installing collected packages: sentinels, dnspython, pymongo, mongomock
Successfully installed dnspython-2.8.0 mongomock-4.3.0 pymongo-4.17.0 sentinels-1.1.1

In [7]:
import pandas as pd

deliveries = pd.read_csv('deliveries.csv')

deliveries.head()

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

In [8]:
from pymongo import MongoClient
import mongomock

client = mongomock.MongoClient()

db = client["northstar_db"]

delivery_collection = db["deliveries"]

delivery_collection.insert_many(
deliveries.to_dict('records')
)

InsertManyResult([ObjectId('6a13543bdcf636852135bfa9'), ObjectId('6a13543bdcf636852135bfaa'), ObjectId('6a13543bdcf636852135bfab'), ObjectId('6a13543bdcf636852135bfac'), ObjectId('6a13543bdcf636852135bfad'), ObjectId('6a13543bdcf636852135bfae'), ObjectId('6a13543bdcf636852135bfaf'), ObjectId('6a13543bdcf636852135bfb0'), ObjectId('6a13543bdcf636852135bfb1'), ObjectId('6a13543bdcf636852135bfb2'), ObjectId('6a13543bdcf636852135bfb3'), ObjectId('6a13543bdcf636852135bfb4'), ObjectId('6a13543bdcf636852135bfb5'), ObjectId('6a13543bdcf636852135bfb6'), ObjectId('6a13543bdcf636852135bfb7'), ObjectId('6a13543bdcf636852135bfb8'), ObjectId('6a13543bdcf636852135bfb9'), ObjectId('6a13543bdcf636852135bfba'), ObjectId('6a13543bdcf636852135bfbb'), ObjectId('6a13543bdcf636852135bfbc'), ObjectId('6a13543bdcf636852135bfbd'), ObjectId('6a13543bdcf636852135bfbe'), ObjectId('6a13543bdcf636852135bfbf'), ObjectId('6a13543bdcf636852135bfc0'), ObjectId('6a13543bdcf636852135bfc1'), ObjectId('6a13543bdcf636852135bfc2'), ObjectId('6a13543bdcf636852135bfc3'), ObjectId('6a13543bdcf636852135bfc4'), ObjectId('6a13543bdcf636852135bfc5'), ObjectId('6a13543bdcf636852135bfc6'), ObjectId('6a13543bdcf636852135bfc7'), ObjectId('6a13543bdcf636852135bfc8'), ObjectId('6a13543bdcf636852135bfc9'), ObjectId('6a13543bdcf636852135bfca'), ObjectId('6a13543bdcf636852135bfcb'), ObjectId('6a13543bdcf636852135bfcc'), ObjectId('6a13543bdcf636852135bfcd'), ObjectId('6a13543bdcf636852135bfce'), ObjectId('6a13543bdcf636852135bfcf'), ObjectId('6a13543bdcf636852135bfd0'), ObjectId('6a13543bdcf636852135bfd1'), ObjectId('6a13543bdcf636852135bfd2'), ObjectId('6a13543bdcf636852135bfd3'), ObjectId('6a13543bdcf636852135bfd4'), ObjectId('6a13543bdcf636852135bfd5'), ObjectId('6a13543bdcf636852135bfd6'), ObjectId('6a13543bdcf636852135bfd7'), ObjectId('6a13543bdcf636852135bfd8'), ObjectId('6a13543bdcf636852135bfd9'), ObjectId('6a13543bdcf636852135bfda'), ObjectId('6a13543bdcf636852135bfdb'), ObjectId('6a13543bdcf636852135bfdc'), ObjectId('6a13543bdcf636852135bfdd'), ObjectId('6a13543bdcf636852135bfde'), ObjectId('6a13543bdcf636852135bfdf'), ObjectId('6a13543bdcf636852135bfe0'), ObjectId('6a13543bdcf636852135bfe1'), ObjectId('6a13543bdcf636852135bfe2'), ObjectId('6a13543bdcf636852135bfe3'), ObjectId('6a13543bdcf636852135bfe4'), ObjectId('6a13543bdcf636852135bfe5'), ObjectId('6a13543bdcf636852135bfe6'), ObjectId('6a13543bdcf636852135bfe7'), ObjectId('6a13543bdcf636852135bfe8'), ObjectId('6a13543bdcf636852135bfe9'), ObjectId('6a13543bdcf636852135bfea'), ObjectId('6a13543bdcf636852135bfeb'), ObjectId('6a13543bdcf636852135bfec'), ObjectId('6a13543bdcf636852135bfed'), ObjectId('6a13543bdcf636852135bfee'), ObjectId('6a13543bdcf636852135bfef'), ObjectId('6a13543bdcf636852135bff0'), ObjectId('6a13543bdcf636852135bff1'), ObjectId('6a13543bdcf636852135bff2'), ObjectId('6a13543bdcf636852135bff3'), ObjectId('6a13543bdcf636852135bff4'), ObjectId('6a13543bdcf636852135bff5'), ObjectId('6a13543bdcf636852135bff6'), ObjectId('6a13543bdcf636852135bff7'), ObjectId('6a13543bdcf636852135bff8'), ObjectId('6a13543bdcf636852135bff9'), ObjectId('6a13543bdcf636852135bffa'), ObjectId('6a13543bdcf636852135bffb'), ObjectId('6a13543bdcf636852135bffc'), ObjectId('6a13543bdcf636852135bffd'), ObjectId('6a13543bdcf636852135bffe'), ObjectId('6a13543bdcf636852135bfff'), ObjectId('6a13543bdcf636852135c000'), ObjectId('6a13543bdcf636852135c001'), ObjectId('6a13543bdcf636852135c002'), ObjectId('6a13543bdcf636852135c003'), ObjectId('6a13543bdcf636852135c004'), ObjectId('6a13543bdcf636852135c005'), ObjectId('6a13543bdcf636852135c006'), ObjectId('6a13543bdcf636852135c007'), ObjectId('6a13543bdcf636852135c008'), ObjectId('6a13543bdcf636852135c009'), ObjectId('6a13543bdcf636852135c00a'), ObjectId('6a13543bdcf636852135c00b'), ObjectId('6a13543bdcf636852135c00c'), ObjectId('6a13543bdcf636852135c00d'), ObjectId('6a13543bdcf636852135c00e'), ObjectId('6a13543bdcf636852135c00f'), ObjectId('6a13543bdcf636852135c010'), ObjectId('6a13543bdcf636852135c011'), ObjectId('6a13543bdcf636852135c012'), ObjectId('6a13543bdcf636852135c013'), ObjectId('6a13543bdcf636852135c014'), ObjectId('6a13543bdcf636852135c015'), ObjectId('6a13543bdcf636852135c016'), ObjectId('6a13543bdcf636852135c017'), ObjectId('6a13543bdcf636852135c018'), ObjectId('6a13543bdcf636852135c019'), ObjectId('6a13543bdcf636852135c01a'), ObjectId('6a13543bdcf636852135c01b'), ObjectId('6a13543bdcf636852135c01c'), ObjectId('6a13543bdcf636852135c01d'), ObjectId('6a13543bdcf636852135c01e'), ObjectId('6a13543bdcf636852135c01f'), ObjectId('6a13543bdcf636852135c020'), ObjectId('6a13543bdcf636852135c021'), ObjectId('6a13543bdcf636852135c022'), ObjectId('6a13543bdcf636852135c023'), ObjectId('6a13543bdcf636852135c024'), ObjectId('6a13543bdcf636852135c025'), ObjectId('6a13543bdcf636852135c026'), ObjectId('6a13543bdcf636852135c027'), ObjectId('6a13543bdcf636852135c028'), ObjectId('6a13543bdcf636852135c029'), ObjectId('6a13543bdcf636852135c02a'), ObjectId('6a13543bdcf636852135c02b'), ObjectId('6a13543bdcf636852135c02c'), ObjectId('6a13543bdcf636852135c02d'), ObjectId('6a13543bdcf636852135c02e'), ObjectId('6a13543bdcf636852135c02f'), ObjectId('6a13543bdcf636852135c030'), ObjectId('6a13543bdcf636852135c031'), ObjectId('6a13543bdcf636852135c032'), ObjectId('6a13543bdcf636852135c033'), ObjectId('6a13543bdcf636852135c034'), ObjectId('6a13543bdcf636852135c035'), ObjectId('6a13543bdcf636852135c036'), ObjectId('6a13543bdcf636852135c037'), ObjectId('6a13543bdcf636852135c038'), ObjectId('6a13543bdcf636852135c039'), ObjectId('6a13543bdcf636852135c03a'), ObjectId('6a13543bdcf636852135c03b'), ObjectId('6a13543bdcf636852135c03c'), ObjectId('6a13543bdcf636852135c03d'), ObjectId('6a13543bdcf636852135c03e'), ObjectId('6a13543bdcf636852135c03f'), ObjectId('6a13543bdcf636852135c040'), ObjectId('6a13543bdcf636852135c041'), ObjectId('6a13543bdcf636852135c042'), ObjectId('6a13543bdcf636852135c043'), ObjectId('6a13543bdcf636852135c044'), ObjectId('6a13543bdcf636852135c045'), ObjectId('6a13543bdcf636852135c046'), ObjectId('6a13543bdcf636852135c047'), ObjectId('6a13543bdcf636852135c048'), ObjectId('6a13543bdcf636852135c049'), ObjectId('6a13543bdcf636852135c04a'), ObjectId('6a13543bdcf636852135c04b'), ObjectId('6a13543bdcf636852135c04c'), ObjectId('6a13543bdcf636852135c04d'), ObjectId('6a13543bdcf636852135c04e'), ObjectId('6a13543bdcf636852135c04f'), ObjectId('6a13543bdcf636852135c050'), ObjectId('6a13543bdcf636852135c051'), ObjectId('6a13543bdcf636852135c052'), ObjectId('6a13543bdcf636852135c053'), ObjectId('6a13543bdcf636852135c054'), ObjectId('6a13543bdcf636852135c055'), ObjectId('6a13543bdcf636852135c056'), ObjectId('6a13543bdcf636852135c057'), ObjectId('6a13543bdcf636852135c058'), ObjectId('6a13543bdcf636852135c059'), ObjectId('6a13543bdcf636852135c05a'), ObjectId('6a13543bdcf636852135c05b'), ObjectId('6a13543bdcf636852135c05c'), ObjectId('6a13543bdcf636852135c05d'), ObjectId('6a13543bdcf636852135c05e'), ObjectId('6a13543bdcf636852135c05f'), ObjectId('6a13543bdcf636852135c060'), ObjectId('6a13543bdcf636852135c061'), ObjectId('6a13543bdcf636852135c062'), ObjectId('6a13543bdcf636852135c063'), ObjectId('6a13543bdcf636852135c064'), ObjectId('6a13543bdcf636852135c065'), ObjectId('6a13543bdcf636852135c066'), ObjectId('6a13543bdcf636852135c067'), ObjectId('6a13543bdcf636852135c068'), ObjectId('6a13543bdcf636852135c069'), ObjectId('6a13543bdcf636852135c06a'), ObjectId('6a13543bdcf636852135c06b'), ObjectId('6a13543bdcf636852135c06c'), ObjectId('6a13543bdcf636852135c06d'), ObjectId('6a13543bdcf636852135c06e'), ObjectId('6a13543bdcf636852135c06f'), ObjectId('6a13543bdcf636852135c070'), ObjectId('6a13543bdcf636852135c071'), ObjectId('6a13543bdcf636852135c072'), ObjectId('6a13543bdcf636852135c073'), ObjectId('6a13543bdcf636852135c074'), ObjectId('6a13543bdcf636852135c075'), ObjectId('6a13543bdcf636852135c076'), ObjectId('6a13543bdcf636852135c077'), ObjectId('6a13543bdcf636852135c078'), ObjectId('6a13543bdcf636852135c079'), ObjectId('6a13543bdcf636852135c07a'), ObjectId('6a13543bdcf636852135c07b'), ObjectId('6a13543bdcf636852135c07c'), ObjectId('6a13543bdcf636852135c07d'), ObjectId('6a13543bdcf636852135c07e'), ObjectId('6a13543bdcf636852135c07f'), ObjectId('6a13543bdcf636852135c080'), ObjectId('6a13543bdcf636852135c081'), ObjectId('6a13543bdcf636852135c082'), ObjectId('6a13543bdcf636852135c083'), ObjectId('6a13543bdcf636852135c084'), ObjectId('6a13543bdcf636852135c085'), ObjectId('6a13543bdcf636852135c086'), ObjectId('6a13543bdcf636852135c087'), ObjectId('6a13543bdcf636852135c088'), ObjectId('6a13543bdcf636852135c089'), ObjectId('6a13543bdcf636852135c08a'), ObjectId('6a13543bdcf636852135c08b'), ObjectId('6a13543bdcf636852135c08c'), ObjectId('6a13543bdcf636852135c08d'), ObjectId('6a13543bdcf636852135c08e'), ObjectId('6a13543bdcf636852135c08f'), ObjectId('6a13543bdcf636852135c090'), ObjectId('6a13543bdcf636852135c091'), ObjectId('6a13543bdcf636852135c092'), ObjectId('6a13543bdcf636852135c093'), ObjectId('6a13543bdcf636852135c094'), ObjectId('6a13543bdcf636852135c095'), ObjectId('6a13543bdcf636852135c096'), ObjectId('6a13543bdcf636852135c097'), ObjectId('6a13543bdcf636852135c098'), ObjectId('6a13543bdcf636852135c099'), ObjectId('6a13543bdcf636852135c09a'), ObjectId('6a13543bdcf636852135c09b'), ObjectId('6a13543bdcf636852135c09c'), ObjectId('6a13543bdcf636852135c09d'), ObjectId('6a13543bdcf636852135c09e'), ObjectId('6a13543bdcf636852135c09f'), ObjectId('6a13543bdcf636852135c0a0'), ObjectId('6a13543bdcf636852135c0a1'), ObjectId('6a13543bdcf636852135c0a2'), ObjectId('6a13543bdcf636852135c0a3'), ObjectId('6a13543bdcf636852135c0a4'), ObjectId('6a13543bdcf636852135c0a5'), ObjectId('6a13543bdcf636852135c0a6'), ObjectId('6a13543bdcf636852135c0a7'), ObjectId('6a13543bdcf636852135c0a8'), ObjectId('6a13543bdcf636852135c0a9'), ObjectId('6a13543bdcf636852135c0aa'), ObjectId('6a13543bdcf636852135c0ab'), ObjectId('6a13543bdcf636852135c0ac'), ObjectId('6a13543bdcf636852135c0ad'), ObjectId('6a13543bdcf636852135c0ae'), ObjectId('6a13543bdcf636852135c0af'), ObjectId('6a13543bdcf636852135c0b0'), ObjectId('6a13543bdcf636852135c0b1'), ObjectId('6a13543bdcf636852135c0b2'), ObjectId('6a13543bdcf636852135c0b3'), ObjectId('6a13543bdcf636852135c0b4'), ObjectId('6a13543bdcf636852135c0b5'), ObjectId('6a13543bdcf636852135c0b6'), ObjectId('6a13543bdcf636852135c0b7'), ObjectId('6a13543bdcf636852135c0b8'), ObjectId('6a13543bdcf636852135c0b9'), ObjectId('6a13543bdcf636852135c0ba'), ObjectId('6a13543bdcf636852135c0bb'), ObjectId('6a13543bdcf636852135c0bc'), ObjectId('6a13543bdcf636852135c0bd'), ObjectId('6a13543bdcf636852135c0be'), ObjectId('6a13543bdcf636852135c0bf'), ObjectId('6a13543bdcf636852135c0c0'), ObjectId('6a13543bdcf636852135c0c1'), ObjectId('6a13543bdcf636852135c0c2'), ObjectId('6a13543bdcf636852135c0c3'), ObjectId('6a13543bdcf636852135c0c4'), ObjectId('6a13543bdcf636852135c0c5'), ObjectId('6a13543bdcf636852135c0c6'), ObjectId('6a13543bdcf636852135c0c7'), ObjectId('6a13543bdcf636852135c0c8'), ObjectId('6a13543bdcf636852135c0c9'), ObjectId('6a13543bdcf636852135c0ca'), ObjectId('6a13543bdcf636852135c0cb'), ObjectId('6a13543bdcf636852135c0cc'), ObjectId('6a13543bdcf636852135c0cd'), ObjectId('6a13543bdcf636852135c0ce'), ObjectId('6a13543bdcf636852135c0cf'), ObjectId('6a13543bdcf636852135c0d0'), ObjectId('6a13543bdcf636852135c0d1'), ObjectId('6a13543bdcf636852135c0d2'), ObjectId('6a13543bdcf636852135c0d3'), ObjectId('6a13543bdcf636852135c0d4'), ObjectId('6a13543bdcf636852135c0d5'), ObjectId('6a13543bdcf636852135c0d6'), ObjectId('6a13543bdcf636852135c0d7'), ObjectId('6a13543bdcf636852135c0d8'), ObjectId('6a13543bdcf636852135c0d9'), ObjectId('6a13543bdcf636852135c0da'), ObjectId('6a13543bdcf636852135c0db'), ObjectId('6a13543bdcf636852135c0dc'), ObjectId('6a13543bdcf636852135c0dd'), ObjectId('6a13543bdcf636852135c0de'), ObjectId('6a13543bdcf636852135c0df'), ObjectId('6a13543bdcf636852135c0e0'), ObjectId('6a13543bdcf636852135c0e1'), ObjectId('6a13543bdcf636852135c0e2'), ObjectId('6a13543bdcf636852135c0e3'), ObjectId('6a13543bdcf636852135c0e4'), ObjectId('6a13543bdcf636852135c0e5'), ObjectId('6a13543bdcf636852135c0e6'), ObjectId('6a13543bdcf636852135c0e7'), ObjectId('6a13543bdcf636852135c0e8'), ObjectId('6a13543bdcf636852135c0e9'), ObjectId('6a13543bdcf636852135c0ea'), ObjectId('6a13543bdcf636852135c0eb'), ObjectId('6a13543bdcf636852135c0ec'), ObjectId('6a13543bdcf636852135c0ed'), ObjectId('6a13543bdcf636852135c0ee'), ObjectId('6a13543bdcf636852135c0ef'), ObjectId('6a13543bdcf636852135c0f0'), ObjectId('6a13543bdcf636852135c0f1'), ObjectId('6a13543bdcf636852135c0f2'), ObjectId('6a13543bdcf636852135c0f3'), ObjectId('6a13543bdcf636852135c0f4'), ObjectId('6a13543bdcf636852135c0f5'), ObjectId('6a13543bdcf636852135c0f6'), ObjectId('6a13543bdcf636852135c0f7'), ObjectId('6a13543bdcf636852135c0f8'), ObjectId('6a13543bdcf636852135c0f9'), ObjectId('6a13543bdcf636852135c0fa'), ObjectId('6a13543bdcf636852135c0fb'), ObjectId('6a13543bdcf636852135c0fc'), ObjectId('6a13543bdcf636852135c0fd'), ObjectId('6a13543bdcf636852135c0fe'), ObjectId('6a13543bdcf636852135c0ff'), ObjectId('6a13543bdcf636852135c100'), ObjectId('6a13543bdcf636852135c101'), ObjectId('6a13543bdcf636852135c102'), ObjectId('6a13543bdcf636852135c103'), ObjectId('6a13543bdcf636852135c104'), ObjectId('6a13543bdcf636852135c105'), ObjectId('6a13543bdcf636852135c106'), ObjectId('6a13543bdcf636852135c107'), ObjectId('6a13543bdcf636852135c108'), ObjectId('6a13543bdcf636852135c109'), ObjectId('6a13543bdcf636852135c10a'), ObjectId('6a13543bdcf636852135c10b'), ObjectId('6a13543bdcf636852135c10c'), ObjectId('6a13543bdcf636852135c10d'), ObjectId('6a13543bdcf636852135c10e'), ObjectId('6a13543bdcf636852135c10f'), ObjectId('6a13543bdcf636852135c110'), ObjectId('6a13543bdcf636852135c111'), ObjectId('6a13543bdcf636852135c112'), ObjectId('6a13543bdcf636852135c113'), ObjectId('6a13543bdcf636852135c114'), ObjectId('6a13543bdcf636852135c115'), ObjectId('6a13543bdcf636852135c116'), ObjectId('6a13543bdcf636852135c117'), ObjectId('6a13543bdcf636852135c118'), ObjectId('6a13543bdcf636852135c119'), ObjectId('6a13543bdcf636852135c11a'), ObjectId('6a13543bdcf636852135c11b'), ObjectId('6a13543bdcf636852135c11c'), ObjectId('6a13543bdcf636852135c11d'), ObjectId('6a13543bdcf636852135c11e'), ObjectId('6a13543bdcf636852135c11f'), ObjectId('6a13543bdcf636852135c120'), ObjectId('6a13543bdcf636852135c121'), ObjectId('6a13543bdcf636852135c122'), ObjectId('6a13543bdcf636852135c123'), ObjectId('6a13543bdcf636852135c124'), ObjectId('6a13543bdcf636852135c125'), ObjectId('6a13543bdcf636852135c126'), ObjectId('6a13543bdcf636852135c127'), ObjectId('6a13543bdcf636852135c128'), ObjectId('6a13543bdcf636852135c129'), ObjectId('6a13543bdcf636852135c12a'), ObjectId('6a13543bdcf636852135c12b'), ObjectId('6a13543bdcf636852135c12c'), ObjectId('6a13543bdcf636852135c12d'), ObjectId('6a13543bdcf636852135c12e'), ObjectId('6a13543bdcf636852135c12f'), ObjectId('6a13543bdcf636852135c130'), ObjectId('6a13543bdcf636852135c131'), ObjectId('6a13543bdcf636852135c132'), ObjectId('6a13543bdcf636852135c133'), ObjectId('6a13543bdcf636852135c134'), ObjectId('6a13543bdcf636852135c135'), ObjectId('6a13543bdcf636852135c136'), ObjectId('6a13543bdcf636852135c137'), ObjectId('6a13543bdcf636852135c138'), ObjectId('6a13543bdcf636852135c139'), ObjectId('6a13543bdcf636852135c13a'), ObjectId('6a13543bdcf636852135c13b'), ObjectId('6a13543bdcf636852135c13c'), ObjectId('6a13543bdcf636852135c13d'), ObjectId('6a13543bdcf636852135c13e'), ObjectId('6a13543bdcf636852135c13f'), ObjectId('6a13543bdcf636852135c140'), ObjectId('6a13543bdcf636852135c141'), ObjectId('6a13543bdcf636852135c142'), ObjectId('6a13543bdcf636852135c143'), ObjectId('6a13543bdcf636852135c144'), ObjectId('6a13543bdcf636852135c145'), ObjectId('6a13543bdcf636852135c146'), ObjectId('6a13543bdcf636852135c147'), ObjectId('6a13543bdcf636852135c148'), ObjectId('6a13543bdcf636852135c149'), ObjectId('6a13543bdcf636852135c14a'), ObjectId('6a13543bdcf636852135c14b'), ObjectId('6a13543bdcf636852135c14c'), ObjectId('6a13543bdcf636852135c14d'), ObjectId('6a13543bdcf636852135c14e'), ObjectId('6a13543bdcf636852135c14f'), ObjectId('6a13543bdcf636852135c150'), ObjectId('6a13543bdcf636852135c151'), ObjectId('6a13543bdcf636852135c152'), ObjectId('6a13543bdcf636852135c153'), ObjectId('6a13543bdcf636852135c154'), ObjectId('6a13543bdcf636852135c155'), ObjectId('6a13543bdcf636852135c156'), ObjectId('6a13543bdcf636852135c157'), ObjectId('6a13543bdcf636852135c158'), ObjectId('6a13543bdcf636852135c159'), ObjectId('6a13543bdcf636852135c15a'), ObjectId('6a13543bdcf636852135c15b'), ObjectId('6a13543bdcf636852135c15c'), ObjectId('6a13543bdcf636852135c15d'), ObjectId('6a13543bdcf636852135c15e'), ObjectId('6a13543bdcf636852135c15f'), ObjectId('6a13543bdcf636852135c160'), ObjectId('6a13543bdcf636852135c161'), ObjectId('6a13543bdcf636852135c162'), ObjectId('6a13543bdcf636852135c163'), ObjectId('6a13543bdcf636852135c164'), ObjectId('6a13543bdcf636852135c165'), ObjectId('6a13543bdcf636852135c166'), ObjectId('6a13543bdcf636852135c167'), ObjectId('6a13543bdcf636852135c168'), ObjectId('6a13543bdcf636852135c169'), ObjectId('6a13543bdcf636852135c16a'), ObjectId('6a13543bdcf636852135c16b'), ObjectId('6a13543bdcf636852135c16c'), ObjectId('6a13543bdcf636852135c16d'), ObjectId('6a13543bdcf636852135c16e'), ObjectId('6a13543bdcf636852135c16f'), ObjectId('6a13543bdcf636852135c170'), ObjectId('6a13543bdcf636852135c171'), ObjectId('6a13543bdcf636852135c172'), ObjectId('6a13543bdcf636852135c173'), ObjectId('6a13543bdcf636852135c174'), ObjectId('6a13543bdcf636852135c175'), ObjectId('6a13543bdcf636852135c176'), ObjectId('6a13543bdcf636852135c177'), ObjectId('6a13543bdcf636852135c178'), ObjectId('6a13543bdcf636852135c179'), ObjectId('6a13543bdcf636852135c17a'), ObjectId('6a13543bdcf636852135c17b'), ObjectId('6a13543bdcf636852135c17c'), ObjectId('6a13543bdcf636852135c17d'), ObjectId('6a13543bdcf636852135c17e'), ObjectId('6a13543bdcf636852135c17f'), ObjectId('6a13543bdcf636852135c180'), ObjectId('6a13543bdcf636852135c181'), ObjectId('6a13543bdcf636852135c182'), ObjectId('6a13543bdcf636852135c183'), ObjectId('6a13543bdcf636852135c184'), ObjectId('6a13543bdcf636852135c185'), ObjectId('6a13543bdcf636852135c186'), ObjectId('6a13543bdcf636852135c187'), ObjectId('6a13543bdcf636852135c188'), ObjectId('6a13543bdcf636852135c189'), ObjectId('6a13543bdcf636852135c18a'), ObjectId('6a13543bdcf636852135c18b'), ObjectId('6a13543bdcf636852135c18c'), ObjectId('6a13543bdcf636852135c18d'), ObjectId('6a13543bdcf636852135c18e'), ObjectId('6a13543bdcf636852135c18f'), ObjectId('6a13543bdcf636852135c190'), ObjectId('6a13543bdcf636852135c191'), ObjectId('6a13543bdcf636852135c192'), ObjectId('6a13543bdcf636852135c193'), ObjectId('6a13543bdcf636852135c194'), ObjectId('6a13543bdcf636852135c195'), ObjectId('6a13543bdcf636852135c196'), ObjectId('6a13543bdcf636852135c197'), ObjectId('6a13543bdcf636852135c198'), ObjectId('6a13543bdcf636852135c199'), ObjectId('6a13543bdcf636852135c19a'), ObjectId('6a13543bdcf636852135c19b'), ObjectId('6a13543bdcf636852135c19c'), ObjectId('6a13543bdcf636852135c19d'), ObjectId('6a13543bdcf636852135c19e'), ObjectId('6a13543bdcf636852135c19f'), ObjectId('6a13543bdcf636852135c1a0'), ObjectId('6a13543bdcf636852135c1a1'), ObjectId('6a13543bdcf636852135c1a2'), ObjectId('6a13543bdcf636852135c1a3'), ObjectId('6a13543bdcf636852135c1a4'), ObjectId('6a13543bdcf636852135c1a5'), ObjectId('6a13543bdcf636852135c1a6'), ObjectId('6a13543bdcf636852135c1a7'), ObjectId('6a13543bdcf636852135c1a8'), ObjectId('6a13543bdcf636852135c1a9'), ObjectId('6a13543bdcf636852135c1aa'), ObjectId('6a13543bdcf636852135c1ab'), ObjectId('6a13543bdcf636852135c1ac'), ObjectId('6a13543bdcf636852135c1ad'), ObjectId('6a13543bdcf636852135c1ae'), ObjectId('6a13543bdcf636852135c1af'), ObjectId('6a13543bdcf636852135c1b0'), ObjectId('6a13543bdcf636852135c1b1'), ObjectId('6a13543bdcf636852135c1b2'), ObjectId('6a13543bdcf636852135c1b3'), ObjectId('6a13543bdcf636852135c1b4'), ObjectId('6a13543bdcf636852135c1b5'), ObjectId('6a13543bdcf636852135c1

In [9]:
pipeline = [
{
"$group": {
"_id": "$delivery_status",
"total_deliveries": {"$sum": 1}
}
}
]

list(
delivery_collection.aggregate(pipeline)
)

[{'total_deliveries': 202, '_id': 'Delayed'},
 {'total_deliveries': 132, '_id': 'Failed'},
 {'total_deliveries': 616, '_id': 'OnTime'}]

In [10]:
pipeline = [
    {
        "$group": {
            "_id": "$delivery_status",
            "average_rating": {
                "$avg": "$customer_rating_post_delivery"
            }
        }
    }
]

list(delivery_collection.aggregate(pipeline))

[{'average_rating': nan, '_id': 'Delayed'},
 {'average_rating': nan, '_id': 'Failed'},
 {'average_rating': nan, '_id': 'OnTime'}]

In [11]:
delivery_collection.create_index("delivery_status")

'delivery_status_1'

In [12]:
delivery_collection.index_information()

{'_id_': {'key': [('_id', 1)], 'v': 2},
 'delivery_status_1': {'key': [('delivery_status', 1)], 'v': 2}}

In [13]:
delivery_collection.find_one()

{'delivery_id': 'DL00001',
 'order_id': 'O00938',
 'driver_id': 'D004',
 'vehicle_id': 'V056',
 'hub_id': 'H05',
 'dispatch_time': '2024-06-18 10:57:00',
 'delivery_completed_at': '2024-06-19 09:05:59.904311',
 'delivery_status': 'Failed',
 'route_distance_km': 17.26,
 'manual_route_override_count': 1,
 'proof_of_completion_missing': 0,
 'customer_rating_post_delivery': 3.07,
 'fuel_or_charge_cost': 12.05,
 '_id': ObjectId('6a13543bdcf636852135bfa9')}

In [14]:
delivery_collection.update_one(
{"delivery_status": "Failed"},
{"$set": {"delivery_status": "Resolved"}}
)

UpdateResult({'connectionId': 2, 'err': None, 'n': 1, 'nModified': 1, 'ok': 1, 'upserted': None, 'updatedExisting': True}, acknowledged=True)

In [15]:
delivery_collection.delete_one(
{"delivery_status": "Resolved"}
)

DeleteResult({'connectionId': 2, 'n': 1, 'ok': 1.0, 'err': None}, acknowledged=True)

In [17]:
delivery_collection.create_index(
"delivery_status"
)

'delivery_status_1'

In [18]:
delivery_collection.index_information()

{'_id_': {'key': [('_id', 1)], 'v': 2},
 'delivery_status_1': {'key': [('delivery_status', 1)], 'v': 2}}

In [20]:
list(
delivery_collection.find(
{"delivery_status": "Delayed"}
).limit(5)
)

[{'delivery_id': 'DL00004',
  'order_id': 'O00313',
  'driver_id': 'D116',
  'vehicle_id': 'V055',
  'hub_id': 'H02',
  'dispatch_time': '2024-03-08 23:31:00',
  'delivery_completed_at': '2024-03-09 23:30:08.103702',
  'delivery_status': 'Delayed',
  'route_distance_km': 16.42,
  'manual_route_override_count': 0,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 4.18,
  'fuel_or_charge_cost': 13.62,
  '_id': ObjectId('6a13543bdcf636852135bfac')},
 {'delivery_id': 'DL00006',
  'order_id': 'O00029',
  'driver_id': 'D037',
  'vehicle_id': 'V098',
  'hub_id': 'H03',
  'dispatch_time': '2024-09-11 12:40:00',
  'delivery_completed_at': '2024-09-12 17:11:52.384869',
  'delivery_status': 'Delayed',
  'route_distance_km': 13.84,
  'manual_route_override_count': 0,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 1.57,
  'fuel_or_charge_cost': 9.58,
  '_id': ObjectId('6a13543bdcf636852135bfae')},
 {'delivery_id': 'DL00007',
  'order_id': 'O00097',
  'driver_id': 'D151',
  'vehicle_id': 'V037',
  'hub_id': 'H07',
  'dispatch_time': '2024-01-09 13:41:00',
  'delivery_completed_at': '2024-01-10 23:39:11.072850',
  'delivery_status': 'Delayed',
  'route_distance_km': 32.72,
  'manual_route_override_count': 0,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 4.64,
  'fuel_or_charge_cost': 17.7,
  '_id': ObjectId('6a13543bdcf636852135bfaf')},
 {'delivery_id': 'DL00017',
  'order_id': 'O01249',
  'driver_id': 'D002',
  'vehicle_id': 'V008',
  'hub_id': 'H05',
  'dispatch_time': '2024-08-25 18:26:00',
  'delivery_completed_at': '2024-08-26 03:05:42.086626',
  'delivery_status': 'Delayed',
  'route_distance_km': 20.79,
  'manual_route_override_count': 0,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 1.0,
  'fuel_or_charge_cost': 15.62,
  '_id': ObjectId('6a13543bdcf636852135bfb9')},
 {'delivery_id': 'DL00028',
  'order_id': 'O00087',
  'driver_id': 'D165',
  'vehicle_id': 'V022',
  'hub_id': 'H08',
  'dispatch_time': '2024-11-12 15:52:00',
  'delivery_completed_at': '2024-11-13 04:15:00.393100',
  'delivery_status': 'Delayed',
  'route_distance_km': 15.53,
  'manual_route_override_count': 2,
  'proof_of_completion_missing': 0,
  'customer_rating_post_delivery': 2.7,
  'fuel_or_charge_cost': 13.05,
  '_id': ObjectId('6a13543bdcf636852135bfc4')}]